name: Django Drip Campaigns Deployment

concurrency: production

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Publish a Python distribution to PyPI
      if: github.head_ref != 'docs/'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
